insert into category (id, title) values (1, 'Sports');
insert into question (id, content, category_id) values (1, 'Sports that start with C', 1);
insert into question (id, content, category_id) values (2, 'Sports that end with L', 1);
insert into question (id, content, category_id) values (3, 'Sports with two syllables', 1);
insert into question (id, content, category_id) values (4, 'Sports with four consonants', 1);
insert into question (id, content, category_id) values (5, 'Sports with a double letter', 1);
insert into question (id, content, category_id) values (6, 'Sports with an S in the middle', 1);
insert into question (id, content, category_id) values (7, 'Sports that end with ball', 1);
insert into question (id, content, category_id) values (8, 'Sports that contain the letter Z', 1);
insert into question (id, content, category_id) values (9, 'Sports that start with a vowel', 1);
insert into question (id, content, category_id) values (10, 'Sports that end with a vowel', 1);
insert into question (id, content, category_id) values (11, 'Sports with five letters', 1);
insert into question (id, content, category_id) values (12, 'Sports with a repeated letter', 1);
insert into question (id, content, category_id) values (13, 'Sports with a K in the middle', 1);
insert into question (id, content, category_id) values (14, 'Sports with an O and an R', 1);
insert into question (id, content, category_id) values (15, 'Sports with exactly six letters', 1);
insert into question (id, content, category_id) values (16, 'Sports with a Y or X', 1);
insert into question (id, content, category_id) values (17, 'Sports that contain TH', 1);
insert into question (id, content, category_id) values (18, 'Sports that are also Olympic events', 1);
insert into question (id, content, category_id) values (19, 'Sports with seven letters', 1);
insert into question (id, content, category_id) values (20, 'Sports that end with ing', 1);
insert into question (id, content, category_id) values (21, 'Sports with consecutive vowels', 1);
insert into question (id, content, category_id) values (22, 'Sports that are also Olympic events', 1);
insert into question (id, content, category_id) values (23, 'Sports that start and end with a vowel', 1);
insert into question (id, content, category_id) values (24, 'Sports that have P as the second letter', 1);
insert into question (id, content, category_id) values (25, 'Sports with a C and an H', 1);
insert into category (id, title) values (2, 'Fruits');
insert into question (id, content, category_id) values (26, 'Fruits that start with P', 2);
insert into question (id, content, category_id) values (27, 'Fruits that end with a vowel', 2);
insert into question (id, content, category_id) values (28, 'Fruits with three syllables', 2);
insert into question (id, content, category_id) values (29, 'Fruits with four consonants', 2);
insert into question (id, content, category_id) values (30, 'Fruits with exactly five letters', 2);
insert into question (id, content, category_id) values (31, 'Fruits with a double letter', 2);
insert into question (id, content, category_id) values (32, 'Fruits that start with a vowel', 2);
insert into question (id, content, category_id) values (33, 'Fruits with seven letters', 2);
insert into question (id, content, category_id) values (34, 'Fruits with an R in the middle', 2);
insert into question (id, content, category_id) values (35, 'Fruits that are berries', 2);
insert into question (id, content, category_id) values (36, 'Fruits with a color in their name', 2);
insert into question (id, content, category_id) values (37, 'Tropical fruits', 2);
insert into question (id, content, category_id) values (38, 'Fruits that can be juiced', 2);
insert into question (id, content, category_id) values (39, 'Fruits with seeds on the outside', 2);
insert into category (id, title) values (3, 'Costumes');
insert into question (id, content, category_id) values (40, 'Costumes that start with P', 3);
insert into question (id, content, category_id) values (41, 'Costumes that end with E', 3);
insert into question (id, content, category_id) values (42, 'Costumes with two syllables', 3);
insert into question (id, content, category_id) values (43, 'Costumes with four consonants', 3);
insert into question (id, content, category_id) values (44, 'Costumes with a double letter', 3);
insert into question (id, content, category_id) values (45, 'Costumes with an S in the middle', 3);
insert into question (id, content, category_id) values (46, 'Costumes that contain the letter Z', 3);
insert into question (id, content, category_id) values (47, 'Costumes that start with a vowel', 3);
insert into question (id, content, category_id) values (48, 'Costumes that end with a vowel', 3);
insert into question (id, content, category_id) values (49, 'Costumes with five letters', 3);
insert into question (id, content, category_id) values (50, 'Costumes with a repeated letter', 3);
insert into question (id, content, category_id) values (51, 'Costumes with a K in the middle', 3);
insert into question (id, content, category_id) values (52, 'Costumes with an O and an R', 3);
insert into question (id, content, category_id) values (53, 'Costumes with exactly six letters', 3);
insert into question (id, content, category_id) values (54, 'Costumes with a Y or X', 3);
insert into question (id, content, category_id) values (55, 'Costumes that contain TH', 3);
insert into question (id, content, category_id) values (56, 'Costumes that start and end with a vowel', 3);
insert into question (id, content, category_id) values (57, 'Costumes with seven letters', 3);
insert into question (id, content, category_id) values (58, 'Costumes that start with G', 3);
insert into question (id, content, category_id) values (59, 'Costumes with a W or Q', 3);
insert into question (id, content, category_id) values (60, 'Costumes that have P as the second letter', 3);
insert into category (id, title) values (4, 'NFL Teams');
insert into question (id, content, category_id) values (61, 'NFL Teams that start with P', 4);
insert into question (id, content, category_id) values (62, 'NFL Teams with two syllables', 4);
insert into question (id, content, category_id) values (63, 'NFL Teams with one syllable', 4);
insert into question (id, content, category_id) values (64, 'NFL Teams with four consonants', 4);
insert into question (id, content, category_id) values (65, 'NFL Teams with a double letter', 4);
insert into question (id, content, category_id) values (66, 'NFL Teams with five letters', 4);
insert into question (id, content, category_id) values (67, 'NFL Teams with exactly six letters', 4);
insert into question (id, content, category_id) values (68, 'NFL Teams that are also bird names', 4);
insert into question (id, content, category_id) values (69, 'NFL Teams that are based in California', 4);
insert into category (id, title) values (5, 'Body Parts');
insert into question (id, content, category_id) values (70, 'Body parts that are commonly tattooed.', 5);
insert into question (id, content, category_id) values (71, 'Body parts that are prone to sunburn.', 5);
insert into question (id, content, category_id) values (72, 'Body parts that can be pierced for jewelry.', 5);
insert into question (id, content, category_id) values (73, 'Body parts that start with F', 5);
insert into question (id, content, category_id) values (74, 'Body parts that end with E', 5);
insert into question (id, content, category_id) values (75, 'Body parts with two syllables', 5);
insert into question (id, content, category_id) values (76, 'Body parts with four consonants', 5);
insert into question (id, content, category_id) values (77, 'Body parts with a double letter', 5);
insert into question (id, content, category_id) values (78, 'Body parts that start with a vowel', 5);
insert into question (id, content, category_id) values (79, 'Body parts that end with a vowel', 5);
insert into question (id, content, category_id) values (80, 'Body parts with five letters', 5);
insert into question (id, content, category_id) values (81, 'Body parts that have P as the second letter', 5);
insert into question (id, content, category_id) values (82, 'Body parts that start with H', 5);
insert into question (id, content, category_id) values (83, 'Body parts that end with S', 5);
insert into category (id, title) values (6, 'Animals');
insert into question (id, content, category_id) values (84, 'Animals that start with L', 6);
insert into question (id, content, category_id) values (85, 'Animals that end with E', 6);
insert into question (id, content, category_id) values (86, 'Animals with two syllables', 6);
insert into question (id, content, category_id) values (87, 'Animals with four legs', 6);
insert into question (id, content, category_id) values (88, 'Animals with a double letter in their name', 6);
insert into question (id, content, category_id) values (89, 'Animals with spots or stripes', 6);
insert into question (id, content, category_id) values (90, 'Animals that can fly', 6);
insert into question (id, content, category_id) values (91, 'Animals that live in the ocean', 6);
insert into question (id, content, category_id) values (92, 'Animals that hibernate', 6);
insert into question (id, content, category_id) values (93, 'Animals with scales', 6);
insert into question (id, content, category_id) values (94, 'Animals that are commonly kept as pets', 6);
insert into question (id, content, category_id) values (95, 'Animals with horns or antlers', 6);
insert into question (id, content, category_id) values (96, 'Animals that are found in the rainforest', 6);
insert into question (id, content, category_id) values (97, 'Animals that are venomous', 6);
insert into question (id, content, category_id) values (98, 'Animals that live in groups', 6);
insert into question (id, content, category_id) values (99, 'Animals with three letters', 6);
insert into question (id, content, category_id) values (100, 'Animals associated with a famous cartoon character', 6);
insert into category (id, title) values (7, 'Cities');
insert into question (id, content, category_id) values (101, 'Cities that start with M', 7);
insert into question (id, content, category_id) values (102, 'Cities that end with A', 7);
insert into question (id, content, category_id) values (103, 'Cities with two syllables', 7);
insert into question (id, content, category_id) values (104, 'Cities with a famous bridge', 7);
insert into question (id, content, category_id) values (105, 'Cities with a population over one million', 7);
insert into question (id, content, category_id) values (106, 'Cities that are capital cities', 7);
insert into question (id, content, category_id) values (107, 'Cities that are known for their historic landmarks', 7);
insert into question (id, content, category_id) values (108, 'Cities that are coastal', 7);
insert into question (id, content, category_id) values (109, 'Cities with a famous skyline', 7);
insert into question (id, content, category_id) values (110, 'Cities with a famous sports team', 7);
insert into question (id, content, category_id) values (111, 'Cities with a major international airport', 7);
insert into question (id, content, category_id) values (112, 'Cities that have hosted the Olympics', 7);
insert into question (id, content, category_id) values (113, 'Cities with a notable historical battle', 7);
insert into question (id, content, category_id) values (114, 'Cities with three syllables', 7);
insert into question (id, content, category_id) values (115, 'Cities with seven letters', 7);
insert into question (id, content, category_id) values (116, 'Cities that start with G', 7);
insert into category (id, title) values (8, 'Colors');
insert into question (id, content, category_id) values (117, 'Colors that start with P', 8);
insert into question (id, content, category_id) values (118, 'Colors that end with E', 8);
insert into question (id, content, category_id) values (119, 'Colors with two syllables', 8);
insert into question (id, content, category_id) values (120, 'Colors with a R in the middle', 8);
insert into question (id, content, category_id) values (121, 'Colors with three syllables', 8);
insert into question (id, content, category_id) values (122, 'Colors that start with C', 8);
insert into question (id, content, category_id) values (123, 'Colors that start with L', 8);
insert into question (id, content, category_id) values (124, 'Colors that start with S', 8);
insert into question (id, content, category_id) values (125, 'Colors that end with L', 8);
insert into question (id, content, category_id) values (126, 'Colors that end with R', 8);
insert into question (id, content, category_id) values (127, 'Colors that end with N', 8);
insert into question (id, content, category_id) values (128, 'Colors with S in the middle', 8);
insert into question (id, content, category_id) values (129, 'Colors with M in the middle', 8);
insert into question (id, content, category_id) values (130, 'Colors with B in the middle', 8);
insert into category (id, title) values (9, 'Languages');
insert into question (id, content, category_id) values (131, 'Languages that start with F', 9);
insert into question (id, content, category_id) values (132, 'Languages that end with a vowel', 9);
insert into question (id, content, category_id) values (133, 'Languages with two syllables', 9);
insert into question (id, content, category_id) values (134, 'Languages with a P in the middle', 9);
insert into question (id, content, category_id) values (135, 'Languages that are official in multiple countries', 9);
insert into question (id, content, category_id) values (136, 'Languages that are widely studied as a second language', 9);
insert into question (id, content, category_id) values (137, 'Languages that start with H', 9);
insert into question (id, content, category_id) values (138, 'Languages that start with L', 9);
insert into category (id, title) values (10, 'Countries');
insert into question (id, content, category_id) values (139, 'Countries that start with A', 10);
insert into question (id, content, category_id) values (140, 'Countries that end with a vowel', 10);
insert into question (id, content, category_id) values (141, 'Countries with two words in their name', 10);
insert into question (id, content, category_id) values (142, 'Countries that are landlocked', 10);
insert into question (id, content, category_id) values (143, 'Countries with a national animal on their flag', 10);
insert into question (id, content, category_id) values (144, 'Countries that have won the FIFA World Cup', 10);
insert into question (id, content, category_id) values (145, 'Countries with a currency using the Euro', 10);
insert into question (id, content, category_id) values (146, 'Countries with a red and white flag', 10);
insert into question (id, content, category_id) values (147, 'Countries with two syllables', 10);
insert into question (id, content, category_id) values (148, 'Countries with three syllables', 10);
insert into question (id, content, category_id) values (149, 'Countries that start with C', 10);
insert into question (id, content, category_id) values (150, 'Countries that start with L', 10);
insert into question (id, content, category_id) values (151, 'Countries that end with N', 10);
insert into question (id, content, category_id) values (152, 'Countries that end with D', 10);
insert into category (id, title) values (11, 'Car Brands');
insert into question (id, content, category_id) values (153, 'Car brands that start with A', 11);
insert into question (id, content, category_id) values (154, 'Car brands that end with a vowel', 11);
insert into question (id, content, category_id) values (155, 'Car brands with two syllables', 11);
insert into question (id, content, category_id) values (156, 'Car brands with a C in their name', 11);
insert into question (id, content, category_id) values (157, 'Car brands with a Formula 1 team', 11);
insert into category (id, title) values (12, 'Candies');
insert into question (id, content, category_id) values (158, 'Candies that start with S', 12);
insert into question (id, content, category_id) values (159, 'Candies that end with a vowel', 12);
insert into question (id, content, category_id) values (160, 'Candies with two syllables', 12);
insert into question (id, content, category_id) values (161, 'Candies that come in various colors', 12);
insert into question (id, content, category_id) values (162, 'Candies with a hard shell', 12);
insert into question (id, content, category_id) values (163, 'Candies that are commonly found in movie theaters', 12);
insert into question (id, content, category_id) values (164, 'Candies that start with T', 12);
insert into question (id, content, category_id) values (165, 'Candies that start with M', 12);
insert into question (id, content, category_id) values (166, 'Candies with an X in their name', 12);
insert into question (id, content, category_id) values (167, 'Candies that end in H', 12);
insert into category (id, title) values (13, 'Cheeses');
insert into question (id, content, category_id) values (168, 'Cheeses that start with G', 13);
insert into question (id, content, category_id) values (169, 'Cheeses that end with a vowel', 13);
insert into question (id, content, category_id) values (170, 'Cheeses with two syllables', 13);
insert into question (id, content, category_id) values (171, 'Cheeses that start with C', 13);
insert into question (id, content, category_id) values (172, 'Cheeses with one syllable', 13);
insert into question (id, content, category_id) values (173, 'Cheeses that are often used in Mexican dishes', 13);
insert into question (id, content, category_id) values (174, 'Cheeses that are often found on charcuterie boards', 13);
insert into question (id, content, category_id) values (175, 'Cheeses that are often used in sandwiches', 13);
insert into category (id, title) values (14, 'Music Genres');
insert into question (id, content, category_id) values (176, 'Music genres that start with H', 14);
insert into question (id, content, category_id) values (177, 'Music genres that end with S', 14);
insert into question (id, content, category_id) values (178, 'Music genres with three syllables', 14);
insert into question (id, content, category_id) values (179, 'Music genres with 3 vowels', 14);
insert into question (id, content, category_id) values (180, 'Music genres that start with R', 14);
insert into question (id, content, category_id) values (181, 'Music genres that end with P', 14);
insert into category (id, title) values (15, 'Cold Things');
insert into question (id, content, category_id) values (182, 'Cold things that start with I', 15);
insert into question (id, content, category_id) values (183, 'Cold things that end with a vowel', 15);
insert into question (id, content, category_id) values (184, 'Cold things with two syllables', 15);
insert into question (id, content, category_id) values (185, 'Cold things with a C in the middle', 15);
insert into question (id, content, category_id) values (186, 'Cold things that are popular in desserts', 15);
insert into question (id, content, category_id) values (187, 'Cold things that are enjoyed on hot summer days', 15);
insert into question (id, content, category_id) values (188, 'Cold things that start with S', 15);
insert into category (id, title) values (16, 'Beer Brands');
insert into question (id, content, category_id) values (189, 'Beer brands that start with M', 16);
insert into question (id, content, category_id) values (190, 'Beer brands that end with S', 16);
insert into question (id, content, category_id) values (191, 'Beer brands with two syllables', 16);
insert into question (id, content, category_id) values (192, 'Beer brands with an R in the middle', 16);
insert into question (id, content, category_id) values (193, 'Beer brands with two words in their name', 16);
insert into category (id, title) values (17, 'Bands/Artists');
insert into question (id, content, category_id) values (194, 'Bands/Artists that start with J', 17);
insert into question (id, content, category_id) values (195, 'Bands/Artists that end with S', 17);
insert into question (id, content, category_id) values (196, 'Bands/Artists with two words in their name', 17);
insert into question (id, content, category_id) values (197, 'Bands/Artists with a K in the middle', 17);
insert into question (id, content, category_id) values (198, 'Bands/Artists with one word in their name', 17);
insert into question (id, content, category_id) values (199, 'Bands/Artists that start with A', 17);
insert into question (id, content, category_id) values (200, 'Bands/Artists that start with B', 17);
insert into question (id, content, category_id) values (201, 'Bands/Artists that start with C', 17);
insert into question (id, content, category_id) values (202, 'Bands/Artists that start with S', 17);
insert into category (id, title) values (18, 'Fast Food Chains');
insert into question (id, content, category_id) values (203, 'Fast Food Chains that start with C', 18);
insert into question (id, content, category_id) values (204, 'Fast Food Chains that end with S', 18);
insert into question (id, content, category_id) values (205, 'Fast Food Chains with two words in their name', 18);
insert into question (id, content, category_id) values (206, 'Fast Food Chains with an N in the middle', 18);
insert into question (id, content, category_id) values (207, 'Fast Food Chains known for their burgers', 18);
insert into question (id, content, category_id) values (208, 'Fast Food Chains known for their pizza', 18);
insert into question (id, content, category_id) values (209, 'Fast Food Chains that start with W', 18);
insert into question (id, content, category_id) values (210, 'Fast Food Chains that start with S', 18);
insert into question (id, content, category_id) values (211, 'Fast Food Chains that start with three vowels', 18);
insert into question (id, content, category_id) values (212, 'Fast Food Chains that start with three syllables', 18);
insert into question (id, content, category_id) values (213, 'Fast Food Chains that start with two syllables', 18);
insert into category (id, title) values (19, 'Green Things');
insert into question (id, content, category_id) values (214, 'Green things that start with S', 19);
insert into question (id, content, category_id) values (215, 'Green things that end with R', 19);
insert into question (id, content, category_id) values (216, 'Green things with two syllables', 19);
insert into question (id, content, category_id) values (217, 'Green things with an A in the middle', 19);
insert into question (id, content, category_id) values (218, 'Green things that are often used in cooking', 19);
insert into question (id, content, category_id) values (219, 'Green things that contain Y or Z', 19);
insert into question (id, content, category_id) values (220, 'Green things that are often found in nature', 19);
insert into category (id, title) values (20, 'Rhymes With');
insert into question (id, content, category_id) values (221, 'Rhymes with Cake', 20);
insert into question (id, content, category_id) values (222, 'Rhymes with Lazy', 20);
insert into question (id, content, category_id) values (223, 'Rhymes with Four', 20);
insert into question (id, content, category_id) values (224, 'Rhymes with Sunny', 20);
insert into question (id, content, category_id) values (225, 'Rhymes with Face', 20);
insert into category (id, title) values (21, 'Fill In The Blank');
insert into question (id, content, category_id) values (226, 'Love is...', 21);
insert into question (id, content, category_id) values (227, 'My boss is...', 21);
insert into question (id, content, category_id) values (228, 'Summer is...', 21);
insert into question (id, content, category_id) values (229, 'Dogs are...', 21);
insert into category (id, title) values (22, 'US States');
insert into question (id, content, category_id) values (230, 'US States that start with N', 22);
insert into question (id, content, category_id) values (231, 'US States that end with A', 22);
insert into question (id, content, category_id) values (232, 'US States with two words in their name', 22);
insert into question (id, content, category_id) values (233, 'US States with a K in the middle', 22);
insert into question (id, content, category_id) values (234, 'US States with a coastline on the Atlantic Ocean', 22);
insert into question (id, content, category_id) values (235, 'US States known for their deserts', 22);
insert into question (id, content, category_id) values (236, 'US States with a significant number of national parks', 22);
insert into question (id, content, category_id) values (237, 'US States with a coastline on the Pacific Ocean', 22);
insert into question (id, content, category_id) values (238, 'US States with a coastline on the Gulf of Mexico', 22);
insert into question (id, content, category_id) values (239, 'US States that share a border with Canada', 22);
insert into question (id, content, category_id) values (240, 'US States that start with New', 22);
insert into question (id, content, category_id) values (241, 'US States that start with W', 22);
insert into question (id, content, category_id) values (242, 'US States that end with a vowel', 22);
insert into question (id, content, category_id) values (243, 'US States with four syllables', 22);
insert into question (id, content, category_id) values (244, 'US States with two syllables', 22);
insert into category (id, title) values (23, 'Foods');
insert into question (id, content, category_id) values (245, 'Foods that start with P', 23);
insert into question (id, content, category_id) values (246, 'Foods that end with E', 23);
insert into question (id, content, category_id) values (247, 'Foods with two words in their name', 23);
insert into question (id, content, category_id) values (248, 'Foods with a H in the middle', 23);
insert into question (id, content, category_id) values (249, 'Foods that are commonly eaten for breakfast', 23);
insert into question (id, content, category_id) values (250, 'Foods that are commonly pickled', 23);
insert into question (id, content, category_id) values (251, 'Foods that are commonly deep-fried', 23);
insert into question (id, content, category_id) values (252, 'Foods with three vowels', 23);
insert into question (id, content, category_id) values (253, 'Foods with two syllables', 23);
insert into question (id, content, category_id) values (254, 'Foods with three syllables', 23);
insert into question (id, content, category_id) values (255, 'Foods that start and end with a vowel', 23);
insert into question (id, content, category_id) values (256, 'Foods with exactly five letters', 23);
insert into question (id, content, category_id) values (257, 'Foods with a double letter', 23);
insert into question (id, content, category_id) values (258, 'Foods that start with a vowel', 23);
insert into question (id, content, category_id) values (259, 'Foods with seven letters', 23);
insert into question (id, content, category_id) values (260, 'Foods with an R in the middle', 23);
insert into category (id, title) values (24, 'Trees');
insert into question (id, content, category_id) values (261, 'Trees that start with M', 24);
insert into question (id, content, category_id) values (262, 'Trees with an O in their name', 24);
insert into question (id, content, category_id) values (263, 'Trees with two words in their name', 24);
insert into question (id, content, category_id) values (264, 'Trees with an L in the middle', 24);
insert into question (id, content, category_id) values (265, 'Trees with three letters', 24);
insert into question (id, content, category_id) values (266, 'Trees that start with A', 24);
insert into question (id, content, category_id) values (267, 'Trees with two syllables', 24);
insert into category (id, title) values (25, 'Famous People');
insert into question (id, content, category_id) values (268, 'Famous people with the first name starting with J', 25);
insert into question (id, content, category_id) values (269, 'Famous people with the last name starting with S', 25);
insert into question (id, content, category_id) values (270, 'Famous people with a W in the middle of their name', 25);
insert into question (id, content, category_id) values (271, 'Famous people known for their contributions to science', 25);
insert into question (id, content, category_id) values (272, 'Famous people with a history of political leadership', 25);
insert into question (id, content, category_id) values (273, 'Famous people with a connection to the entertainment industry', 25);
insert into question (id, content, category_id) values (274, 'Famous people with a connection to space exploration', 25);
insert into question (id, content, category_id) values (275, 'Famous people with a history of philanthropy', 25);
insert into question (id, content, category_id) values (276, 'Famous people known for their contributions to literature', 25);
insert into question (id, content, category_id) values (277, 'Famous people with the first name starting with T', 25);
insert into question (id, content, category_id) values (278, 'Famous people with the last name starting with P', 25);
insert into category (id, title) values (26, 'Movie Franchises');
insert into question (id, content, category_id) values (279, 'Movie franchises that start with P', 26);
insert into question (id, content, category_id) values (280, 'Movie franchises that start with S', 26);
insert into question (id, content, category_id) values (281, 'Movie franchises with a name based on a book', 26);
insert into question (id, content, category_id) values (282, 'Movie franchises with a video game adaptation', 26);
insert into question (id, content, category_id) values (283, 'Movie franchises known for their iconic villains', 26);
insert into question (id, content, category_id) values (284, 'Movie franchises that have won Academy Awards', 26);
insert into question (id, content, category_id) values (285, 'Movie franchises that start with A', 26);
insert into question (id, content, category_id) values (286, 'Movie franchises that start with H', 26);
insert into category (id, title) values (27, 'Books');
insert into question (id, content, category_id) values (287, 'Books that start with M', 27);
insert into question (id, content, category_id) values (288, 'Books that start with R', 27);
insert into question (id, content, category_id) values (289, 'Books with two-word titles', 27);
insert into question (id, content, category_id) values (290, 'Books with an N in the middle', 27);
insert into question (id, content, category_id) values (291, 'Books with one-word titles', 27);
insert into question (id, content, category_id) values (292, 'Books that have been adapted into movies', 27);
insert into question (id, content, category_id) values (293, 'Books with a name inspired by a historical event', 27);
insert into question (id, content, category_id) values (294, 'Books that are often required reading in schools', 27);
insert into question (id, content, category_id) values (295, 'Books known for their strong female protagonists', 27);
insert into question (id, content, category_id) values (296, 'Books with and in the title', 27);
insert into question (id, content, category_id) values (297, 'Books that start with A', 27);
insert into question (id, content, category_id) values (298, 'Books that start with C', 27);
insert into category (id, title) values (28, 'Periodic Table');
insert into question (id, content, category_id) values (299, 'Elements on the periodic table that start with C', 28);
insert into question (id, content, category_id) values (300, 'Elements on the periodic table that end with N', 28);
insert into question (id, content, category_id) values (301, 'Elements on the periodic table with two-letter symbols', 28);
insert into question (id, content, category_id) values (302, 'Elements on the periodic table with a Y in their name', 28);
insert into question (id, content, category_id) values (303, 'Elements on the periodic table with single-letter symbols', 28);
insert into question (id, content, category_id) values (304, 'Elements on the periodic table that are noble gases', 28);
insert into question (id, content, category_id) values (305, 'Elements on the periodic table that start with N', 28);
insert into question (id, content, category_id) values (306, 'Elements on the periodic table that end with M', 28);
insert into category (id, title) values (29, 'Mythical Creatures');
insert into question (id, content, category_id) values (307, 'Mythical creatures that start with G', 29);
insert into question (id, content, category_id) values (308, 'Mythical creatures that end with S', 29);
insert into question (id, content, category_id) values (309, 'Mythical creatures with two-word names', 29);
insert into question (id, content, category_id) values (310, 'Mythical creatures with a P in their name', 29);
insert into question (id, content, category_id) values (311, 'Mythical creatures with two syllables', 29);
insert into question (id, content, category_id) values (312, 'Mythical creatures with three vowels', 29);
insert into question (id, content, category_id) values (313, 'Mythical creatures with five letters', 29);
insert into question (id, content, category_id) values (314, 'Mythical creatures with six letters', 29);
insert into category (id, title) values (30, 'Famous Brands');
insert into question (id, content, category_id) values (315, 'Famous brands that start with C', 30);
insert into question (id, content, category_id) values (316, 'Famous brands that end with R', 30);
insert into question (id, content, category_id) values (317, 'Famous brands with two-word names', 30);
insert into question (id, content, category_id) values (318, 'Famous brands with a K in their name', 30);
insert into question (id, content, category_id) values (319, 'Famous brands with red logos', 30);
insert into question (id, content, category_id) values (320, 'Famous brands with a name inspired by a founders surname', 30);
insert into question (id, content, category_id) values (321, 'Famous brands with a focus on sportswear and athletics', 30);
insert into question (id, content, category_id) values (322, 'Famous brands that start with B', 30);
insert into question (id, content, category_id) values (323, 'Famous brands that end with E', 30);
insert into question (id, content, category_id) values (324, 'Famous brands with a focus on technology', 30);
insert into category (id, title) values (31, ' stars');
insert into question (id, content, category_id) values (325, 'Planets', 31);
insert into question (id, content, category_id) values (326, 'Planets', 31);
insert into question (id, content, category_id) values (327, 'Planets', 31);
insert into question (id, content, category_id) values (328, 'Planets', 31);
insert into question (id, content, category_id) values (329, 'Planets', 31);
insert into question (id, content, category_id) values (330, 'Planets', 31);
insert into question (id, content, category_id) values (331, 'Planets', 31);
insert into question (id, content, category_id) values (332, 'Planets', 31);
insert into category (id, title) values (32, 'Flowers');
insert into question (id, content, category_id) values (333, 'Flowers that start with R', 32);
insert into question (id, content, category_id) values (334, 'Flowers that end with Y', 32);
insert into question (id, content, category_id) values (335, 'Flowers with two-word names', 32);
insert into question (id, content, category_id) values (336, 'Flowers with a P in their name', 32);
insert into question (id, content, category_id) values (337, 'Flowers known for their vibrant colors', 32);
insert into question (id, content, category_id) values (338, 'Flowers with a history of medicinal uses', 32);
insert into question (id, content, category_id) values (339, 'Flowers used in perfumes', 32);
insert into question (id, content, category_id) values (340, 'Flowers that start with D', 32);
insert into question (id, content, category_id) values (341, 'Flowers that end with A', 32);
insert into question (id, content, category_id) values (342, 'Flowers with two syllables', 32);
insert into question (id, content, category_id) values (343, 'Flowers with five letters', 32);
insert into question (id, content, category_id) values (344, 'Flowers with a double letter', 32);
insert into question (id, content, category_id) values (345, 'Flowers that start and end in a vowel', 32);
